# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  RID: 'linux-x64'

stages:
- stage: Build
  jobs:
  - job: PublishandTest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime $(RID) --self-contained false'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/**Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: NETCoreApp_Dev 
  dependsOn: Build
  jobs:
  - deployment: MyNETCoreDev 
    displayName: DeployingNETCore-Dev
    environment:
      name: NET-Core-dev
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: Stop NET Core Service
            inputs:
              script: echo $(PASSWORD) | sudo -S systemctl stop dotnet-web

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              downloadPath: '$(Agent.BuildDirectory)'
              artifactName: 'drop'

          - task: ExtractFiles@1
            displayName: Extract zip file to ~/wwww
            inputs:
              archiveFilePatterns: '/home/jcelestino/azagent/azagent/_work/1/drop/s.zip'
              destinationFolder: '/home/jcelestino/www'
              cleanDestinationFolder: false
              overwriteExistingFiles: true
          
          - task: CmdLine@2
            displayName: Start Service
            inputs:
              script: echo $(PASSWORD) | sudo -S systemctl start dotnet-web

- stage: NETCoreApp_STG
  dependsOn: NETCoreApp_Dev
  jobs:
    - deployment: MyNETCoreStg
      displayName: DeployingNETCore-Stg
      environment:
        name: NET-Core-stg
        resourceType: VirtualMachine
      strategy:
       runOnce:
         deploy:
           steps:
           - task: CmdLine@2
             displayName: Stop NET Core Service
             inputs:
              script: echo $(PASSWORD) | sudo -S systemctl stop dotnet-web

           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               downloadPath: '$(Agent.BuildDirectory)'
               artifactName: 'drop'

           - task: ExtractFiles@1
             displayName: Extract zip file to ~/wwww
             inputs:
               archiveFilePatterns: '/home/jcelestino/azagent/azagent/_work/1/drop/s.zip'
               destinationFolder: '/home/jcelestino/www'
               cleanDestinationFolder: false
               overwriteExistingFiles: true
          
           - task: CmdLine@2
             displayName: Start Service
             inputs:
              script: echo $(PASSWORD) | sudo -S systemctl start dotnet-web