# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: PublishandTest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/**Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: NETCoreAppDeployment
  jobs:
  - deployment: MyNETCoreDeploy
    displayName: DeployingNETCore
    environment:
      name: NET-Core-dev
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: Extract zip file to ~/wwww
            inputs:
              script: 'unzip s.zip -d /home/jcelestino/www'
              workingDirectory: '/home/jcelestino/azagent/_work/1/drop'
          - task: CmdLine@2
            displayName: dotnet run
            inputs:
              script: 'dotnet dotnet-web.dll'
              workingDirectory: '/home/jcelestino/www'
